ilk-django-projem/blog/urls.py
from django.urls import path
from blog.views import home, post_detay

urlpatterns = [
    path('', home, name='blog_list'),
    path('<post_link>/', post_detay, name='blog_detay')

]

ilk-django-projem/config/urls.py
from xml.dom.expatbuilder import Namespaces
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from config.views import home #, ad_soyad_yaz, isim_yaz,python
from django.urls import include, path 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('kullanici/', include('django.contrib.auth.urls')),
    path('wallet/', include('wallet.urls', namespace='wallet')),
    path('__debug__/', include('debug_toolbar.urls')),

    path('', home, name='home'),
    # path('python/', python),
    # path('<isim>/', isim_yaz), 
    # path('<ad>/<soyad>/', ad_soyad_yaz),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ilk-django-projem/wallet/urls.py
from django.urls import path
from wallet.views import add_wallet, remove_wallet
app_name = 'wallet'
urlpatterns = [
    path('new', add_wallet, name='wallet_add'),
    path('<cuzdan_id>/sil/', remove_wallet, name="wallet_remove"),
]

ilk-django-projem/blog/models.py
from django.db import models


# Create your models here.
class Post(models.Model):
    yayinla = models.BooleanField(default=False)
    baslik = models.CharField(max_length=200, unique=True)
    link = models.SlugField(max_length=200, unique=True)
    resim = models.ImageField(upload_to ='blog_resim/')
    icerik = models.TextField()
    olusturma = models.DateTimeField(auto_now_add=True)
    guncelleme = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.baslik

ilk-django-projem/vip/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Subscribe(models.Model):
    class USER_TYPE(models.TextChoices):
        Bronz = 'BR', 'Bronz'
        Gold = 'GD', 'Gold'
        Platinum = 'PL', 'Platinum'
        PlatinumPlus = 'PP', 'Platinum Plus'
        free = 'FR', 'Bedavaci'

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='subscribe')
    type = models.CharField(max_length=2, choices=USER_TYPE.choices, default=USER_TYPE.free)

    def __str__(self):
        return self.user.username

    def get_badge_url(self):
        return static('bronz.png')

ilk-django-projem/wallet/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Cuzdan(models.Model):
    class PARA_BIRIMLERI(models.TextChoices):
        USD = 'USD', 'Dolar'
        EUR = 'EUR', 'Euro'
        TL = 'TL', 'Turk Lirasi'
        BTC = 'BTC', 'Bitcoin'

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cuzdanlar')
    para_birimi = models.CharField(max_length=3, choices=PARA_BIRIMLERI.choices,
        default=PARA_BIRIMLERI.TL)
    bakiye = models.DecimalField(max_digits=6, decimal_places=2)

    class Meta:
        unique_together = ('user', 'para_birimi',)

    def __str__(self):
        return self.user.first_name + ': ' + str(self.bakiye) + self.para_birimi

    def get_absolute_url(self):
        return reverse('wallet:wallet_remove', kwargs={'cuzdan_id':self.id})

    

ilk-django-projem/wallet/forms.py
from dataclasses import field
from django import forms
from wallet.models import Cuzdan

class CuzdanForm(forms.ModelForm):
    class Meta:
        model = Cuzdan
        fields = ['para_birimi']

ilk-django-projem/blog/views.py
from django.shortcuts import render, get_object_or_404
from blog.models import Post

def home(request):
    # postlar = Post.objects.all()
    yayinlanmis_postlar = Post.objects.filter(yayinla=True)

    context = {
        'postlar': yayinlanmis_postlar
    }

    return render(request, 'blog_list.html', context)

def post_detay(request,post_link):
    # post = Post.objects.get(link=post_link, yayinla=True)

    post = get_object_or_404(Post, link=post_link, yayinla=True)

    context = {
        'post': post
    }
    return render(request, 'blog_detay.html', context)

ilk-django-projem/config/views.py
from django.shortcuts import render
from django.http import HttpResponse

def home(request):
    context = {}

    if request.user.is_authenticated:
        context['cuzdanlar'] = request.user.cuzdanlar.all()

    return render(request, 'index.html', context)

def isim_yaz(request, isim):
    return render(request, 'isim.html', {'isim': isim})

def python(request):
    return HttpResponse('Bunu goremezsin.')

def ad_soyad_yaz(request, ad, soyad):
    return render(request, 'adsoyad.html', {'ad': ad, 'soyad':soyad})
    

ilk-django-projem/vip/views.py
from django.shortcuts import render

# Create your views here.

ilk-django-projem/wallet/views.py
from django.shortcuts import render, redirect, get_object_or_404
from wallet.forms import CuzdanForm
from wallet.models import Cuzdan

# Create your views here.
def add_wallet(request):
    context = {}
    form = CuzdanForm(request.POST or None)
    if form.is_valid():
        wallet = form.save(commit=False)
        wallet.user =request.user
        wallet.bakiye = 50
        wallet.save()
        return redirect ('/')

    context['form'] = form
    return render(request, 'add_wallet.html', context)

def remove_wallet(request, cuzdan_id):
    cuzdan = get_object_or_404(Cuzdan, id=cuzdan_id, user=request.user)
    cuzdan.delete()
    return redirect('/')

ilk-django-projem/templates/add_wallet.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Ekle</button>
</form>
{% endblock %}

ilk-django-projem/templates/adsoyad.html
{{ ad }}
{{ soyad }}

ilk-django-projem/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block header %}
{% include 'menu.html' %}
{% endblock %}

{% block content %}
{% endblock%}

<br><br><br>

{% block footer %}
Tum Haklari saklidir. C {% now 'Y' %}
{% endblock %}
</body>
</html>

ilk-django-projem/templates/blog_detay.html
{% extends 'base.html' %}
{% block content %}
<center>
<h1>{{ post.baslik }}</h1>
<a href="{% url 'blog_list' %}">Geri</a>
<img src="{{ post.resim.url }}" alt="" width="200" height="200">
<p>{{ post.icerik }}</p>
</center>
{% endblock %}

ilk-django-projem/templates/blog_list.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
<center>
    
<h1>OYK Python 2022 Blog</h1>   
<br><br><br><br> 
<h2>Blog Listesi</h2>


{% for post in postlar %}
    <h3><a href="{% url 'blog_detay' post.link %}">{{ post.baslik }}</a></h3>
    <p>Olusturma: {{ post.olusturma|naturaltime }}, Guncelleme: {{ post.guncelleme|naturaltime }}</p>
    <img src="{{ post.resim.url }}" alt="{{ post.baslik }}" width="250" height="200">
    <p>{{ post.icerik|truncatechars:80 }}</p>
    <a href="{% url 'blog_detay' post.link %}">Detay</a>
{% endfor %}
</center>

{% endblock %}

ilk-django-projem/templates/index.html
{% extends 'base.html' %}

{% block content %}

<br><br><br>

{% if request.user.is_authenticated %}

Hosgeldin {{ request.user.get_full_name }}
<h3>Cuzdanlariniz</h3><a href="{% url 'wallet:wallet_add' %}">Cuzdan Ekle</a><br><br>
{% for cuzdan in cuzdanlar %}
<b>{{ cuzdan.get_para_birimi_display }} : </b>{{ cuzdan.bakiye }}{{cuzdan.para_birimi}} <a href="{{ cuzdan.get_absolute_url }}">sil</a> <br>
{% empty %}
Hicbir cuzdan bulunamadi, lutfen cuzdan ekleyin.
{% endfor %}

{% else %}

Bakiyeyi gormek icin giris yapmalisin.

{% endif %}


<br><br><br><br><br><br>
<h1>Home</h1>
<h2>Simdiki zaman</h2>
{% now "H:i" %}
{% lorem %}

{% endblock %}

ilk-django-projem/templates/isim.html
{{ isim }}

ilk-django-projem/templates/menu.html
{% load static %}
<style>
ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333333;
}

li {
  float: left;
}

li a {
  display: block;
  color: white;
  text-align: center;
  padding: 16px;
  text-decoration: none;
}

li a:hover {
  background-color: #111111;
}
</style>
<ul>
    <li><img src="{% static 'logo.png' %}" width="50" height="50" alt="My image"></li>
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'blog_list' %}">Blog</a></li>
    {% if request.user.is_authenticated %}

    <li style="color:white>{{request.usr.get_full_name}}</li>
    <li style="float=right">{{request.usr.get_full_name}}</li>

    
    <li style="float:right"><a href="{% url 'logout' %}">Cikis Yap</a></li>
    {% else %}
    <li style="float:right"><a href="{% url 'login' %}">Giris Yap</a></li>
    {% endif %}
    
</ul>